### ISSUE TITLE
Alpha Support

### ISSUE THREAD

**Issue by WaldemarLehner** [LuizZak/FastBitmap#10]
I was wondering if there are any plans on adding support for an alpha channel

**Comment by LuizZak** [comment]
I've thought about it since another issue where someone brought it up. I've refrained from adding alpha channel initially because I knew for sure I'd get it wrong and then we'd be stuck with some alpha channel implementation that wasn't correct or didn't work when using pre-multiplied bitmaps or something like that.

I'm open to suggestions related to alpha channel, but still I think it'd be hard to get it right (and fast!) on the first try.
