### ISSUE TITLE
Convert to bitmap

### ISSUE THREAD

**Issue by JanTamis-zz** [LuizZak/FastBitmap#8]
Hello ik have a question, how can i convert the fastbitmap to a bitmap?

**Comment by WaldemarLehner** [comment]
Got the same question
@JanTamis .. since you closed the Issue yourself, did you find a solution?

**Comment by JanTamis-zz** [comment]
I did find a solution: in the source code there is this variable
<code>private readonly Bitmap _bitmap; </code>
 if you chance this to
<code>public readonly Bitmap _bitmap; </code>
then you have a using bitmap

please note that you need to keep it readonly.

**Comment by WaldemarLehner** [comment]
ah. ok. I fiddled around with my code and apparently one can just convert the FastBitmap by simply doing
Bitmap bitmap = myfastbitmap and vice versa.

**Comment by JanTamis-zz** [comment]
i have tried that but it did not work.

**Comment by WaldemarLehner** [comment]
![image](https://user-images.githubusercontent.com/27686785/35779226-c685a592-09c9-11e8-9ee1-cef53d8e5067.png)
Weird. That way I made this work.
The image was made pixel by pixel from a json and for the scaling in the lower left corner I converted it to normal bitmap and used Graphics.Fromimage(bitmap).

**Comment by JanTamis-zz** [comment]
do you use the nuget package?

**Comment by WaldemarLehner** [comment]
yes i do

**Comment by JanTamis-zz** [comment]
aah maybe there is a difference between the nuget package and the source code

**Comment by JanTamis-zz** [comment]
i would be nice if the developer could tell us.

**Comment by WaldemarLehner** [comment]
might be. If you want to I can send you my code.. maybe it could help you.

**Comment by JanTamis-zz** [comment]
i would be nice

**Comment by JanTamis-zz** [comment]
i dont know if it is smart to chance the variable to public

**Comment by WaldemarLehner** [comment]
I mean.. it really depends on what you are doing.

**Comment by JanTamis-zz** [comment]
i am creating a image processing class for my CCreative library and i need the bitmap so i can draw it in GDI+ and opengl

**Comment by WaldemarLehner** [comment]
https://github.com/WaldemarLehner/EDEDSMVisualizer/blob/feature/gridlines/EDEDSMVisualizer/pages/Generation.xaml.cs#L379
The code is horrible, not commented.. but maybe it ill help you.

**Comment by WaldemarLehner** [comment]
bitmap is a FastBitmap while _bitmap is a regular Bitmap

**Comment by JanTamis-zz** [comment]
i think there is a difference to the nuget package and the source code 

ps i copied the source code onto my project.

**Comment by WaldemarLehner** [comment]
I mean.. in that case.. try the nuget package 😄

**Comment by JanTamis-zz** [comment]
i am trying to use as less as possible but maybe it is better. thank you for your comment.

**Comment by WaldemarLehner** [comment]
you're welcome :) good luck!

**Comment by JanTamis-zz** [comment]
lol i came to help you but you helped me. good luck to you to.

**Comment by LuizZak** [comment]
Heyo! Looks like I came a little late to the party, but anyways...

The reason I left `_bitmap` private was to encourage using `FastBitmap` as a thin layer that you'd use locally whenever you needed to manipulate a bitmap. Since FastBitmap works mostly by locking and unlocking the bitmap's memory region using `LockBits`, it doesn't make sense to keep the bitmap locked further than a couple of operations, since to use the bitmap again to paint to the screen etc. you need the bitmap to be unlocked anyways, so creating and using FastBitmaps only within the methods that need them made more sense to me, and that allows `_bitmap` to be hidden away.

If possible, I recommend passing the original `Bitmap` around method parameters and lock/unlock `FastBitmap`'s locally, or wrap the Bitmap+FastBitmap pair on a structure and pass that instead.

**Comment by JanTamis-zz** [comment]
Thank you for your response :)
